# Generated by Django 4.2.11 on 2025-08-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0003_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='items/'),
        ),
    ]
