# Generated by Django 4.2.11 on 2025-08-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0004_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Image',
            field=models.ImageField(default=' ', upload_to='items/'),
            preserve_default=False,
        ),
    ]
