# Generated by Django 4.2.11 on 2025-08-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0005_feedback_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktable',
            name='Ratings',
        ),
    ]
